apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtfg
  template:
    metadata:
      labels:
        app: rtfg
    spec:
      containers:
      - image: okteto.dev/rtfg:latest
        name: rtfg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "c353b860-c4dc-4e77-81e6-2f3705225c8a"
        - name: Vless_Path
          value: "/orgh"
        - name: Vmess_UUID
          value: "c353b860-c4dc-4e77-81e6-2f3705225c8a"
        - name: Vmess_Path
          value: "/fnmhy"
        - name: Share_Path
          value: "/share233"
