apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgrs
  template:
    metadata:
      labels:
        app: bgrs
    spec:
      containers:
      - image: okteto.dev/bgrs:latest
        name: bgrs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "0a6ca853-f912-47c9-ba3d-07fc1750302f"
        - name: Vless_Path
          value: "/dbhty"
        - name: Vmess_UUID
          value: "0a6ca853-f912-47c9-ba3d-07fc1750302f"
        - name: Vmess_Path
          value: "/mksdd"
        - name: Share_Path
          value: "/share233"
