apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cxer
  template:
    metadata:
      labels:
        app: cxer
    spec:
      containers:
      - image: okteto.dev/cxer:latest
        name: cxer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "104b8b62-ef22-4c29-bba5-c2f6fc8ee44e"
        - name: Vless_Path
          value: "/jude"
        - name: Vmess_UUID
          value: "104b8b62-ef22-4c29-bba5-c2f6fc8ee44e"
        - name: Vmess_Path
          value: "/mvde"
        - name: Share_Path
          value: "/share233"
