apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sjf
  template:
    metadata:
      labels:
        app: sjf
    spec:
      containers:
      - image: okteto.dev/sjf:latest
        name: sjf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "18879636-809e-4f4d-ab4b-4045796377c9"
        - name: Vless_Path
          value: "/mvbshbd"
        - name: Vmess_UUID
          value: "18879636-809e-4f4d-ab4b-4045796377c9"
        - name: Vmess_Path
          value: "/sjfkdk"
        - name: Share_Path
          value: "/share233"
