apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcer
  template:
    metadata:
      labels:
        app: wcer
    spec:
      containers:
      - image: okteto.dev/wcer:latest
        name: wcer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "ed882052-374c-4a48-9d7b-f61bb2620d80"
        - name: Vless_Path
          value: "/kgbgf"
        - name: Vmess_UUID
          value: "ed882052-374c-4a48-9d7b-f61bb2620d80"
        - name: Vmess_Path
          value: "/xcfdvf"
        - name: Share_Path
          value: "/share233"
