apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gen
  template:
    metadata:
      labels:
        app: gen
    spec:
      containers:
      - image: okteto.dev/gen:latest
        name: gen
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "freemp3cloud.com"
        - name: Vless_UUID
          value: "8b8a0437-6d2b-499e-807f-7ff50b928b64"
        - name: Vless_Path
          value: "/wsdr56hujbbgcf"
        - name: Vmess_UUID
          value: "8b8a0437-6d2b-499e-807f-7ff50b928b64"
        - name: Vmess_Path
          value: "/9pvfdmnhb45red"
        - name: Share_Path
          value: "/share233"
