apiVersion: apps/v1
kind: Deployment
metadata:
  name: vfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vfr
  template:
    metadata:
      labels:
        app: vfr
    spec:
      containers:
      - image: okteto.dev/vfr:latest
        name: vfr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.canva.com"
        - name: Vless_UUID
          value: "9e5d4588-4f3b-4c9a-8c60-bbaebb5fd02c"
        - name: Vless_Path
          value: "/bgtff"
        - name: Vmess_UUID
          value: "9e5d4588-4f3b-4c9a-8c60-bbaebb5fd02c"
        - name: Vmess_Path
          value: "/mkiol"
        - name: Share_Path
          value: "/share233"
