apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfvgrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bfvgrt
  template:
    metadata:
      labels:
        app: bfvgrt
    spec:
      containers:
      - image: okteto.dev/bfvgrt:latest
        name: bfvgrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "c810a1f0-21d9-4cc0-b071-b4cf62febbbc"
        - name: Vless_Path
          value: "/bntyty"
        - name: Vmess_UUID
          value: "c810a1f0-21d9-4cc0-b071-b4cf62febbbc"
        - name: Vmess_Path
          value: "/muuikuf"
        - name: Share_Path
          value: "/share233"
