apiVersion: apps/v1
kind: Deployment
metadata:
  name: vffes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vffes
  template:
    metadata:
      labels:
        app: vffes
    spec:
      containers:
      - image: okteto.dev/vffes:latest
        name: vffes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "12ef6f4e-52b1-4b8a-aaad-09a7a02cb3d7"
        - name: Vless_Path
          value: "/gtnjccv"
        - name: Vmess_UUID
          value: "12ef6f4e-52b1-4b8a-aaad-09a7a02cb3d7"
        - name: Vmess_Path
          value: "/sdfdlo"
        - name: Share_Path
          value: "/share233"
