apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfgtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bfgtt
  template:
    metadata:
      labels:
        app: bfgtt
    spec:
      containers:
      - image: okteto.dev/bfgtt:latest
        name: bfgtt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "cd9d29a3-5f15-4d95-9efc-90c847e01d4b"
        - name: Vless_Path
          value: "/ntyty"
        - name: Vmess_UUID
          value: "cd9d29a3-5f15-4d95-9efc-90c847e01d4b"
        - name: Vmess_Path
          value: "/mujuyy"
        - name: Share_Path
          value: "/share233"
