apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnt
  template:
    metadata:
      labels:
        app: bnt
    spec:
      containers:
      - image: okteto.dev/bnt:latest
        name: bnt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "1f216ecc-50b7-4ac2-8723-866b289e7813"
        - name: Vless_Path
          value: "/drtgt"
        - name: Vmess_UUID
          value: "1f216ecc-50b7-4ac2-8723-866b289e7813"
        - name: Vmess_Path
          value: "/juyyn"
        - name: Share_Path
          value: "/share233"
