apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbts
  template:
    metadata:
      labels:
        app: fbts
    spec:
      containers:
      - image: okteto.dev/fbts:latest
        name: fbts
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "8f5467f0-4460-488a-9c30-d02ea24116ed"
        - name: Vless_Path
          value: "/bmye"
        - name: Vmess_UUID
          value: "8f5467f0-4460-488a-9c30-d02ea24116ed"
        - name: Vmess_Path
          value: "/sfgty"
        - name: Share_Path
          value: "/share233"
