apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnghn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnghn
  template:
    metadata:
      labels:
        app: vnghn
    spec:
      containers:
      - image: okteto.dev/vnghn:latest
        name: vnghn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "5c33bd0c-2796-45b1-87c5-8136bed55e87"
        - name: Vless_Path
          value: "/nhmjhvf"
        - name: Vmess_UUID
          value: "5c33bd0c-2796-45b1-87c5-8136bed55e87"
        - name: Vmess_Path
          value: "/csdcdvfd"
        - name: Share_Path
          value: "/share233"
