apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdvrg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdvrg
  template:
    metadata:
      labels:
        app: cdvrg
    spec:
      containers:
      - image: okteto.dev/cdvrg:latest
        name: cdvrg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "07b71969-b8e6-447e-8544-3b537c66741e"
        - name: Vless_Path
          value: "/yhsdb"
        - name: Vmess_UUID
          value: "07b71969-b8e6-447e-8544-3b537c66741e"
        - name: Vmess_Path
          value: "/nmopffd"
        - name: Share_Path
          value: "/share233"
