apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikop
  template:
    metadata:
      labels:
        app: ikop
    spec:
      containers:
      - image: okteto.dev/ikop:latest
        name: ikop
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "7117b65d-9baf-4699-bde8-42f09305a09b"
        - name: Vless_Path
          value: "/cvfret"
        - name: Vmess_UUID
          value: "7117b65d-9baf-4699-bde8-42f09305a09b"
        - name: Vmess_Path
          value: "/nmmjyu"
        - name: Share_Path
          value: "/share233"
