apiVersion: apps/v1
kind: Deployment
metadata:
  name: odjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odjs
  template:
    metadata:
      labels:
        app: odjs
    spec:
      containers:
      - image: okteto.dev/odjs:latest
        name: odjs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "61e0c0d6-add7-47fa-9460-9f91a6914a28"
        - name: Vless_Path
          value: "/vnmdef"
        - name: Vmess_UUID
          value: "61e0c0d6-add7-47fa-9460-9f91a6914a28"
        - name: Vmess_Path
          value: "/pskur"
        - name: Share_Path
          value: "/share233"
