apiVersion: apps/v1
kind: Deployment
metadata:
  name: tjki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tjki
  template:
    metadata:
      labels:
        app: tjki
    spec:
      containers:
      - image: okteto.dev/tjki:latest
        name: tjki
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "0d1a12a8-4ed3-4e7e-8819-474d099cc842"
        - name: Vless_Path
          value: "/mjkios"
        - name: Vmess_UUID
          value: "0d1a12a8-4ed3-4e7e-8819-474d099cc842"
        - name: Vmess_Path
          value: "/cdfre"
        - name: Share_Path
          value: "/share233"
