apiVersion: apps/v1
kind: Deployment
metadata:
  name: bga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bga
  template:
    metadata:
      labels:
        app: bga
    spec:
      containers:
      - image: okteto.dev/bga:latest
        name: bga
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.freemusicarchive.org"
        - name: Vless_UUID
          value: "1439313a-8791-4cd7-a214-9c9e51f1a50f"
        - name: Vless_Path
          value: "/nmhydf"
        - name: Vmess_UUID
          value: "1439313a-8791-4cd7-a214-9c9e51f1a50f"
        - name: Vmess_Path
          value: "/mkopl"
        - name: Share_Path
          value: "/share233"
