apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oldf
  template:
    metadata:
      labels:
        app: oldf
    spec:
      containers:
      - image: okteto.dev/oldf:latest
        name: oldf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "29492624-ba2f-416d-b1a2-15bc65237cce"
        - name: Vless_Path
          value: "/vfbgfgt"
        - name: Vmess_UUID
          value: "29492624-ba2f-416d-b1a2-15bc65237cce"
        - name: Vmess_Path
          value: "/rtfgbf"
        - name: Share_Path
          value: "/share233"
