apiVersion: apps/v1
kind: Deployment
metadata:
  name: khg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khg
  template:
    metadata:
      labels:
        app: khg
    spec:
      containers:
      - image: okteto.dev/khg:latest
        name: khg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "0c463867-3e69-4587-9145-63cc62ad8bec"
        - name: Vless_Path
          value: "/bgngh"
        - name: Vmess_UUID
          value: "0c463867-3e69-4587-9145-63cc62ad8bec"
        - name: Vmess_Path
          value: "/ngxdgbgf"
        - name: Share_Path
          value: "/share233"
