apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdv
  template:
    metadata:
      labels:
        app: bdv
    spec:
      containers:
      - image: okteto.dev/bdv:latest
        name: bdv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "de01682e-7ec7-4fc2-8250-52d1b8332468"
        - name: Vless_Path
          value: "/bfrtgt"
        - name: Vmess_UUID
          value: "de01682e-7ec7-4fc2-8250-52d1b8332468"
        - name: Vmess_Path
          value: "/bfbgfd"
        - name: Share_Path
          value: "/share233"
