apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvjd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvjd
  template:
    metadata:
      labels:
        app: mvjd
    spec:
      containers:
      - image: okteto.dev/mvjd:latest
        name: mvjd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "6f8a2cff-a269-4609-b009-5d73bef64310"
        - name: Vless_Path
          value: "/jgklksj"
        - name: Vmess_UUID
          value: "6f8a2cff-a269-4609-b009-5d73bef64310"
        - name: Vmess_Path
          value: "/mashgjd"
        - name: Share_Path
          value: "/share233"
