apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfas
  template:
    metadata:
      labels:
        app: tfas
    spec:
      containers:
      - image: okteto.dev/tfas:latest
        name: tfas
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "4d390efb-6303-466b-9d44-d1e0a11b51b7"
        - name: Vless_Path
          value: "/bgyjhg"
        - name: Vmess_UUID
          value: "4d390efb-6303-466b-9d44-d1e0a11b51b7"
        - name: Vmess_Path
          value: "/kzsscf"
        - name: Share_Path
          value: "/share233"
