apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntd
  template:
    metadata:
      labels:
        app: ntd
    spec:
      containers:
      - image: okteto.dev/ntd:latest
        name: ntd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "6a77cbe9-b0fd-4c6b-96e6-7dc4810ce3bb"
        - name: Vless_Path
          value: "/rbhty"
        - name: Vmess_UUID
          value: "6a77cbe9-b0fd-4c6b-96e6-7dc4810ce3bb"
        - name: Vmess_Path
          value: "/nghxcg"
        - name: Share_Path
          value: "/share233"
