apiVersion: apps/v1
kind: Deployment
metadata:
  name: hehds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hehds
  template:
    metadata:
      labels:
        app: hehds
    spec:
      containers:
      - image: okteto.dev/hehds:latest
        name: hehds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "d971d8b6-8b90-44a2-a78f-9c83c1ff696a"
        - name: Vless_Path
          value: "/vbftd"
        - name: Vmess_UUID
          value: "d971d8b6-8b90-44a2-a78f-9c83c1ff696a"
        - name: Vmess_Path
          value: "/cnmyus"
        - name: Share_Path
          value: "/share233"
