apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrzc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vrzc
  template:
    metadata:
      labels:
        app: vrzc
    spec:
      containers:
      - image: okteto.dev/vrzc:latest
        name: vrzc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "58ef1fb8-de16-4272-8312-303a92dcf51a"
        - name: Vless_Path
          value: "/uibfdd"
        - name: Vmess_UUID
          value: "58ef1fb8-de16-4272-8312-303a92dcf51a"
        - name: Vmess_Path
          value: "/mklfvd"
        - name: Share_Path
          value: "/share233"
