apiVersion: apps/v1
kind: Deployment
metadata:
  name: nythtyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nythtyt
  template:
    metadata:
      labels:
        app: nythtyt
    spec:
      containers:
      - image: okteto.dev/nythtyt:latest
        name: nythtyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "4c27f6c3-78ce-484b-bf68-f4c90e70e6e4"
        - name: Vless_Path
          value: "/bgnhgds"
        - name: Vmess_UUID
          value: "4c27f6c3-78ce-484b-bf68-f4c90e70e6e4"
        - name: Vmess_Path
          value: "/ujdfvft"
        - name: Share_Path
          value: "/share233"
