apiVersion: apps/v1
kind: Deployment
metadata:
  name: xzdcds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xzdcds
  template:
    metadata:
      labels:
        app: xzdcds
    spec:
      containers:
      - image: okteto.dev/xzdcds:latest
        name: xzdcds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "0c5b9727-9e68-4a07-a7a8-17788e50c9e8"
        - name: Vless_Path
          value: "/bnhty"
        - name: Vmess_UUID
          value: "0c5b9727-9e68-4a07-a7a8-17788e50c9e8"
        - name: Vmess_Path
          value: "/yufffgf"
        - name: Share_Path
          value: "/share233"
