apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsvf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsvf
  template:
    metadata:
      labels:
        app: bsvf
    spec:
      containers:
      - image: okteto.dev/bsvf:latest
        name: bsvf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "dcbf88fd-f530-4d4f-be72-e7481d9b36d6"
        - name: Vless_Path
          value: "/obddf"
        - name: Vmess_UUID
          value: "dcbf88fd-f530-4d4f-be72-e7481d9b36d6"
        - name: Vmess_Path
          value: "/nmtcsr"
        - name: Share_Path
          value: "/share233"
