apiVersion: apps/v1
kind: Deployment
metadata:
  name: frbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frbd
  template:
    metadata:
      labels:
        app: frbd
    spec:
      containers:
      - image: okteto.dev/frbd:latest
        name: frbd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "1ff7b2f5-57d5-44cb-bcbd-0165167c20a8"
        - name: Vless_Path
          value: "/bnyf"
        - name: Vmess_UUID
          value: "1ff7b2f5-57d5-44cb-bcbd-0165167c20a8"
        - name: Vmess_Path
          value: "/vbrds"
        - name: Share_Path
          value: "/share233"
