apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcvrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcvrr
  template:
    metadata:
      labels:
        app: xcvrr
    spec:
      containers:
      - image: okteto.dev/xcvrr:latest
        name: xcvrr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "1b947922-7785-4f63-8b6b-5cb93d318f9d"
        - name: Vless_Path
          value: "/bnthy"
        - name: Vmess_UUID
          value: "1b947922-7785-4f63-8b6b-5cb93d318f9d"
        - name: Vmess_Path
          value: "/mujuf"
        - name: Share_Path
          value: "/share233"
