apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdsg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdsg
  template:
    metadata:
      labels:
        app: bdsg
    spec:
      containers:
      - image: okteto.dev/bdsg:latest
        name: bdsg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "70a67f34-25e2-4f0c-a095-7a14ea72e746"
        - name: Vless_Path
          value: "/uidfcv"
        - name: Vmess_UUID
          value: "70a67f34-25e2-4f0c-a095-7a14ea72e746"
        - name: Vmess_Path
          value: "/mklsd"
        - name: Share_Path
          value: "/share233"
